# Generated by Django 3.2.13 on 2022-04-18 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CompantName', models.CharField(blank=True, max_length=256, null=True)),
                ('ClientName', models.CharField(blank=True, max_length=256, null=True)),
                ('PhoneNo', models.CharField(blank=True, max_length=10, null=True)),
                ('email', models.CharField(blank=True, max_length=10, null=True)),
                ('city', models.CharField(blank=True, max_length=128, null=True)),
                ('certificate', models.CharField(blank=True, max_length=128, null=True)),
                ('body', models.CharField(blank=True, max_length=512, null=True)),
                ('rate', models.CharField(blank=True, max_length=128, null=True)),
                ('issueDate', models.DateField(blank=True, null=True)),
                ('expiryDate', models.DateField(blank=True, null=True)),
                ('expiryYear', models.CharField(blank=True, max_length=128, null=True)),
                ('remark', models.CharField(blank=True, max_length=128, null=True)),
            ],
        ),
    ]
