# Generated by Django 3.2.13 on 2022-04-18 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0005_statuslist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companylist',
            name='client_key',
        ),
        migrations.RemoveField(
            model_name='statuslist',
            name='client_key',
        ),
        migrations.DeleteModel(
            name='CertificateList',
        ),
        migrations.DeleteModel(
            name='client',
        ),
        migrations.DeleteModel(
            name='CompanyList',
        ),
        migrations.DeleteModel(
            name='StatusList',
        ),
    ]
