# Generated by Django 3.2.13 on 2022-04-18 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userapp', '0006_auto_20220418_1201'),
    ]

    operations = [
        migrations.CreateModel(
            name='client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=128, null=True)),
                ('PhoneNo', models.CharField(blank=True, max_length=10, null=True)),
                ('email', models.CharField(blank=True, max_length=10, null=True)),
                ('password', models.CharField(blank=True, max_length=10, null=True)),
                ('otp', models.CharField(default=359, max_length=6)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='StatusList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statusList', models.CharField(blank=True, max_length=128, null=True)),
                ('client_key', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='userapp.client')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=128, null=True)),
                ('client_key', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='userapp.client')),
            ],
        ),
        migrations.CreateModel(
            name='ClientCompanyList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CompantName', models.CharField(blank=True, max_length=256, null=True)),
                ('ClientName', models.CharField(blank=True, max_length=256, null=True)),
                ('PhoneNo', models.CharField(blank=True, max_length=10, null=True)),
                ('email', models.CharField(blank=True, max_length=10, null=True)),
                ('city', models.CharField(blank=True, max_length=128, null=True)),
                ('certificate', models.CharField(blank=True, max_length=128, null=True)),
                ('body', models.CharField(blank=True, max_length=512, null=True)),
                ('rate', models.CharField(blank=True, max_length=128, null=True)),
                ('issueDate', models.DateField(blank=True, null=True)),
                ('expiryDate', models.DateField(blank=True, null=True)),
                ('expiryYear', models.CharField(blank=True, max_length=128, null=True)),
                ('remark', models.CharField(blank=True, max_length=128, null=True)),
                ('status', models.CharField(blank=True, max_length=128, null=True)),
                ('client_key', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='userapp.client')),
            ],
        ),
        migrations.CreateModel(
            name='CertificateList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificateName', models.CharField(blank=True, max_length=128, null=True)),
                ('client_key', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='userapp.client')),
            ],
        ),
    ]
