# Generated by Django 3.2.13 on 2022-04-18 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0007_certificatelist_client_clientcompanylist_companylist_statuslist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
