# Generated by Django 3.2.13 on 2022-04-19 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0008_alter_client_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=1000)),
                ('value', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='clientcompanylist',
            name='status',
            field=models.CharField(blank=True, default='Renew', max_length=128, null=True),
        ),
    ]
