# Generated by Django 3.2.13 on 2022-04-20 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0010_alter_clientcompanylist_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='AndroidSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phoneNo', models.CharField(blank=True, max_length=10, null=True)),
                ('otp', models.CharField(blank=True, default=963852, max_length=6, null=True)),
                ('iemi', models.CharField(blank=True, max_length=512, null=True)),
                ('fcmtocken', models.CharField(blank=True, max_length=512, null=True)),
            ],
        ),
    ]
