# Generated by Django 3.2.13 on 2022-04-20 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0011_androidsetting'),
    ]

    operations = [
        migrations.RenameField(
            model_name='androidsetting',
            old_name='phoneNo',
            new_name='mobileNumber',
        ),
    ]
