# Generated by Django 3.2.13 on 2022-04-21 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0012_rename_phoneno_androidsetting_mobilenumber'),
    ]

    operations = [
        migrations.RenameField(
            model_name='androidsetting',
            old_name='otp',
            new_name='OTP',
        ),
    ]
