# Generated by Django 3.2.13 on 2022-04-25 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0013_rename_otp_androidsetting_otp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='androidsetting',
            old_name='iemi',
            new_name='imei',
        ),
    ]
