# Generated by Django 3.2.13 on 2022-04-25 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0014_rename_iemi_androidsetting_imei'),
    ]

    operations = [
        migrations.CreateModel(
            name='signIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobileNumber', models.CharField(blank=True, max_length=10, null=True)),
                ('OTP', models.CharField(blank=True, default=963852, max_length=6, null=True)),
            ],
        ),
    ]
