# Generated by Django 3.2.13 on 2022-04-27 23:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0016_androidsetting_phonetype'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotifactionSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nList', models.CharField(blank=True, max_length=128, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('client_key', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='userapp.client')),
            ],
        ),
    ]
