# Generated by Django 3.2.13 on 2022-04-29 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0017_notifactionsetting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='androidsetting',
            name='phoneType',
            field=models.CharField(blank=True, default='Android', max_length=128, null=True),
        ),
    ]
