# Generated by Django 3.2.13 on 2022-04-29 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0018_alter_androidsetting_phonetype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notifactionsetting',
            name='is_active',
        ),
    ]
