# Generated by Django 3.2.13 on 2022-05-04 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0020_auto_20220429_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifactionsetting',
            name='emailService',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='notifactionsetting',
            name='fcmService',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='notifactionsetting',
            name='smsService',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='notifactionsetting',
            name='voiceNotiService',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
